[uwsgi]
plugins = python3
chdir = /opt/patchwork
module = patchwork.wsgi:application
master = true
processes = 4
socket = /run/patchwork/uwsgi.sock
chmod-socket = 660
buffer-size = 16384
vacuum = true
